Reimplement synthesis allocation
chipmunk-project/chipmunk pull request #151
Opened 2019-06-21 14:27 UTC by XiangyuG

2019-06-21 14:27 UTC, pep8speaks commented
Hello @XiangyuG! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`chipc/compiler.py`](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/compiler.py):

> [Line 43:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/compiler.py#L43): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)



* In the file [`chipc/sketch_generator.py`](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py):

> [Line 267:16](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L267): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 267:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L267): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 269:16](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L269): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 274:16](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L274): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 274:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L274): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 276:16](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L276): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 289:12](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/chipc/sketch_generator.py#L289): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

* In the file [`tests/test_chipmunk.py`](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py):

> [Line 36:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 62:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 86:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 101:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L101): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 112:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L112): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 128:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L128): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 136:80](https://github.com/chipmunk-project/chipmunk/blob/cf71e069586386934665141d2ff4ef6999292781/tests/test_chipmunk.py#L136): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2019-06-21 15:13 UTC, taegyunkim requested changes

2019-06-21 15:13 UTC, taegyunkim commented on chipc/compiler.py
> +                 parallel_sketch, synthesized_allocation, pkt_fields_to_check=[]):
Set default value here. 

```suggestion
                 parallel_sketch, synthesized_allocation=False, pkt_fields_to_check=[]):
```

2019-06-21 15:13 UTC, taegyunkim commented on chipc/iterative_solver.py
> +        help='Making it set means to use synthesized allocation'
```suggestion
        help='If set let sketch allocate state variables otherwise \
              use canonical allocation, i.e, first state variable assigned \
              to first phv container.'
```

2019-06-21 15:13 UTC, taegyunkim commented on tests/test_chipmunk.py
> +                2, 'simple', parallel_sketch=False, synthesized_allocation=False)
This can be removed if you set the default value.

2019-06-21 15:18 UTC, taegyunkim requested changes
1. Add tests
2. Add command line argument in direct_solver.py 
3. Get rid of one state restrictions.

2019-06-22 12:30 UTC, XiangyuG commented on tests/test_chipmunk.py
> +                2, 'simple', parallel_sketch=False, synthesized_allocation=False)
Solved.

2019-06-23 03:43 UTC, taegyunkim approved these changes

2019-06-23 03:46 UTC, taegyunkim requested changes
Please fix pep8 warnings

2019-06-23 03:46 UTC, taegyunkim commented
> Hello @XiangyuG! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`chipc/compiler.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/compiler.py):
> 
> > [Line 43:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/compiler.py#L43): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> 
> * In the file [`chipc/direct_solver.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/direct_solver.py):
> 
> > [Line 44:6](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/direct_solver.py#L44): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> > [Line 55:59](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/direct_solver.py#L55): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> 
> * In the file [`chipc/optverify_stub_generator.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py):
> 
> > [Line 31:75](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py#L31): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> > [Line 31:77](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py#L31): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> > [Line 31:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> 
> * In the file [`chipc/sketch_generator.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py):
> 
> > [Line 266:16](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L266): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> > [Line 266:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> > [Line 268:16](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L268): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> > [Line 273:16](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L273): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> > [Line 273:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L273): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> > [Line 275:16](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L275): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> > [Line 288:12](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L288): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> 
> * In the file [`tests/test_iterative_solver.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/tests/test_iterative_solver.py):
> 
> > [Line 38:1](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/tests/test_iterative_solver.py#L38): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> > [Line 60:1](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/tests/test_iterative_solver.py#L60): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> > [Line 70:10](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/tests/test_iterative_solver.py#L70): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> > [Line 148:1](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/tests/test_iterative_solver.py#L148): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> > [Line 149:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/tests/test_iterative_solver.py#L149): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> 
> ##### Comment last updated at 2019-06-23 02:04:30 UTC

Plex 

> Hello @XiangyuG! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`chipc/compiler.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/compiler.py):
> 
> > [Line 43:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/compiler.py#L43): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> 
> * In the file [`chipc/direct_solver.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/direct_solver.py):
> 
> > [Line 44:6](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/direct_solver.py#L44): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> > [Line 55:59](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/direct_solver.py#L55): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> 
> * In the file [`chipc/optverify_stub_generator.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py):
> 
> > [Line 31:75](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py#L31): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> > [Line 31:77](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py#L31): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> > [Line 31:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/optverify_stub_generator.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> 
> * In the file [`chipc/sketch_generator.py`](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py):
> 
> > [Line 266:16](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L266): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> > [Line 266:80](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> > [Line 268:16](https://github.com/chipmunk-project/chipmunk/blob/c40d91e7685e8286b2a4f87a9add815e03cc6c5f/chipc/sketch_generator.py#L268): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> > [Line 273:16](https://github.com/chipmunk-pr [...]

2019-06-23 04:15 UTC, anirudhSK commented on chipc/sketch_generator.py
> +        for i in range(self.num_pipeline_stages_):
What is the point of this line and the line below? Can we remove the for i ... and the if (i==0). We just need to execute the code within the if (i==0) once, correct?

2019-06-23 04:28 UTC, anirudhSK commented
> Please fix pep8 warnings

Been fixed now.

2019-06-23 04:47 UTC, taegyunkim requested changes

2019-06-23 04:47 UTC, taegyunkim commented on chipc/sketch_generator.py
> +        for i in range(self.num_pipeline_stages_):
Also why is this necessary for when i == 0?

2019-06-23 04:47 UTC, taegyunkim commented on chipc/sketch_generator.py
> +                    assert_predicate += '0) <= 1'
Note that you can avoid having trailing 0 by using a combination of map() and string.join(). It's fine as is.

For example, 
```
' + '.join(
    map(
        lambda k: 'phv_config_' + str(i) + '_' + str(k) + '_' + str(j), 
        range(self.num_fields_in_prog_)
    ) 
)
```

2019-06-23 13:18 UTC, XiangyuG commented on chipc/sketch_generator.py
> +                    assert_predicate += '0) <= 1'
This is a really good idea. Now I just name phv_config_{field}_{container} so we can avoid str(i) now.

2019-06-23 14:37 UTC, taegyunkim approved these changes

2019-06-23 14:47 UTC, anirudhSK approved these changes

2019-06-23 14:49 UTC, merged