ALU working and includes universal grammar for stateless and stateful
chipmunk-project/chipmunk pull request #157
Opened 2019-07-19 20:33 UTC by aatish17varma

https://www.youtube.com/watch?v=xpVfcZ0ZcFM

2019-07-20 00:42 UTC, anirudhSK commented
Thanks for resolving these issues. Why is there a file temp/alu.g4? Is it used anywhere? Also in the last commit, it seems like it's taking forever to run some unit tests. Can we run those tests on cyclops to see what's going on?

2019-07-20 00:52 UTC, anirudhSK commented
@mdw362 and @aatish17varma 

I ran the unit tests on cyclops. 19 of them fail. The most common error message seems to be:

AssertionError: Error:  type is declared as stateful and not 'stateless' for stateless ALU

Here's a test that causes this error:

anirudh@cyclops:~/chipmunk$ python3 -m unittest tests.test_iterative_solver.IterativeSolverTest.test_times_two_hole_elimination
Iteration #1
ANTLR runtime and generated code versions disagree: 4.7.2!=4.5.1
ANTLR runtime and generated code versions disagree: 4.7.2!=4.5.1
F
======================================================================
FAIL: test_times_two_hole_elimination (tests.test_iterative_solver.IterativeSolverTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anirudh/chipmunk/tests/test_iterative_solver.py", line 246, in test_times_two_hole_elimination
    '3', '3', '10', '--hole-elimination']),
  File "/home/anirudh/chipmunk/chipc/iterative_solver.py", line 167, in main
    additional_testcases=additional_testcases)
  File "/home/anirudh/chipmunk/chipc/compiler.py", line 135, in serial_codegen
    str(iter_cnt) + '.sk'))
  File "/home/anirudh/chipmunk/chipc/compiler.py", line 101, in single_codegen_run
    additional_testcases=additional_testcases)
  File "/home/anirudh/chipmunk/chipc/sketch_generator.py", line 267, in generate_sketch
    alu_definitions = self.generate_alus()
  File "/home/anirudh/chipmunk/chipc/sketch_generator.py", line 238, in generate_alus
    for k in range(0, self.num_phv_containers_)
  File "/home/anirudh/chipmunk/chipc/sketch_generator.py", line 92, in generate_stateless_alu
    stateless_alu_sketch_generator.visit(tree)
  File "/home/anirudh/.local/lib/python3.5/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/anirudh/chipmunk/chipc/aluParser.py", line 2493, in accept
    return visitor.visitAlu(self)
  File "/home/anirudh/chipmunk/chipc/stateless_alu_sketch_generator.py", line 38, in visitAlu
    self.visit(ctx.getChild(0, aluParser.State_indicatorContext))
  File "/home/anirudh/.local/lib/python3.5/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/anirudh/chipmunk/chipc/aluParser.py", line 507, in accept
    return visitor.visitState_indicator(self)
  File "/home/anirudh/chipmunk/chipc/stateless_alu_sketch_generator.py", line 73, in visitState_indicator
    ' and not \'stateless\' for stateless ALU '
AssertionError: Error:  type is declared as stateful and not 'stateless' for stateless ALU 

----------------------------------------------------------------------
Ran 1 test in 0.040s

FAILED (failures=1)

2019-07-20 02:32 UTC, anirudhSK commented
I fixed the assertion error from the command above, but the unit tests are taking much longer than the unit tests at the master branch. The number of hole bits in the generated sketch files also seem to be different from before.

2019-07-20 13:32 UTC, mdw362 commented
The test_simple_raw_succeeds_with_two_two_grid will never pass after the recent changes. The new structure of the stateless ALU functions is different from the old layout within the Sketch file in tests/data resulting in differing hole variables/values so the last assertion will always fail.

2019-07-20 15:43 UTC, anirudhSK commented
@mdw362: Thanks for these changes. Unlike before, the unit tests run to completion on AppVeyor now, but 4 of them still fail. Two questions.

1. Can we check that the number of hole bits in all the generated sketches (belonging to the test suite) are the same before and after applying this pull request? You can determine the number of hole bits by searching for the string "Total number of hole bits is ..." This still only tells us that the number of hole bits in the generated sketch is the same as before---not that the generated sketches themselves are the same---but it's still a good sanity check.

2. I don't understand why "test_simple_raw_succeeds_with_two_two_grid will never pass." Could you explain this in more detail? If we need to change the reference output in the unit tests because the names of the holes have changed, we can do that.

2019-07-20 16:32 UTC, mdw362 commented
@anirudhSK
1. Okay I can try that and compare the hole bits once this build completes

2. The test_simple_raw_succeeds_with_two_two_grid function inside of tests/test_chipmunk.py asserts that the two dicts output_holes and expected_holes are equivalent. However, because of my changes in the structure of how stateless ALUs are used, the names of the holes are different. I've attached txt files showing the differences. By just eyeballing it, you can see that the hole bits are the same and it's just the names that are different (unless I missed something).
[output.txt](https://github.com/chipmunk-project/chipmunk/files/3413791/output.txt)
[expected.txt](https://github.com/chipmunk-project/chipmunk/files/3413792/expected.txt)

2019-07-21 13:50 UTC, anirudhSK commented on chipc/templates/router_data_path_sketch_synthesized_allocation.j2
> +        input_0_{{field_number}} = state_and_packet.pkt_{{field_number}};
Why did we change this? @XiangyuG: introduced this change in https://github.com/chipmunk-project/chipmunk/pull/151 for benchmarking. I think we need to revert this and the other change to router_data_path_sketch_synthesized_allocation.j2.

2019-07-21 13:50 UTC, anirudhSK commented on chipc/templates/router_data_path_sketch_synthesized_allocation.j2
> +    state_and_packet.pkt_{{field_number}} = output_{{num_pipeline_stages - 1}}_{{field_number}};
Same comments as above.

2019-07-21 15:16 UTC, anirudhSK requested changes

2019-07-21 15:16 UTC, anirudhSK commented on example_alus/stateless_alus/stateless_alu_arith.alu
> +// Max value of opcode is 4
These numbers are 1 less than what they were previously. Also, the max value of opcode was used to determine the opcode bit width previously. Are we still doing that now?

2019-07-21 15:16 UTC, anirudhSK commented on chipc/templates/router_data_path_sketch_synthesized_allocation.j2
> +    state_and_packet.pkt_{{field_number}} = output_{{num_pipeline_stages - 1}}_{{field_number}};
Why did we change this? @XiangyuG: introduced this change in #151 for benchmarking. I think we need to revert this and the other change to router_data_path_sketch_synthesized_allocation.j2.

2019-07-21 15:16 UTC, anirudhSK commented on chipc/templates/router_data_path_sketch_synthesized_allocation.j2
> +        input_0_{{field_number}} = state_and_packet.pkt_{{field_number}};
Why did we change this? @XiangyuG: introduced this change in https://github.com/chipmunk-project/chipmunk/pull/151 for benchmarking. I think we need to revert this and the other change to router_data_path_sketch_synthesized_allocation.j2.

2019-07-21 15:16 UTC, anirudhSK commented on example_alus/stateless_alus/stateless_alu_arith_rel.alu
> +// Max value of opcode is 12
Same comment as before on max value of opcode.

2019-07-21 15:16 UTC, anirudhSK commented on example_alus/stateless_alus/stateless_alu_arith_rel_cond.alu
> +// Max value of opcode is 14
Same comment as before on max value of opcode.

2019-07-21 15:16 UTC, anirudhSK commented on example_alus/stateless_alus/stateless_alu_arith_rel_cond_bool.alu
> +// Max value of opcode is 19
Same comment as before on max value of opcode.

2019-07-21 15:16 UTC, anirudhSK commented on chipc/sketch_generator.py
> -            '_mux2_ctrl)')  # symmetry breaking for commutativity
Do we have these symmetry breaking asserts in the new code as well?

2019-07-21 15:16 UTC, anirudhSK commented on chipc/stateful_alu_sketch_generator.py
> +    def visitUpdates(self, ctx):
Can we add the overrides annotation to all functions that we override?

2019-07-21 15:19 UTC, anirudhSK commented
@XiangyuG and @taegyunkim: Can you look at this as well? It's a more invasive change, so would be good to take a closer look.

2019-07-21 15:26 UTC, taegyunkim commented
I'll review this before dinner today.

2019-07-21 15:59 UTC, anirudhSK requested changes

2019-07-21 15:59 UTC, anirudhSK commented on chipc/sketch_generator.py
>          mux_op_3 = self.generate_mux(
Can we determine the number of such operand muxes from the .alu file instead of hardcoding it to 3?

2019-07-21 17:34 UTC, taegyunkim requested changes

2019-07-21 17:34 UTC, taegyunkim commented on chipc/generator_tester.py
> +def main(argv):
What does this file do? What is the purpose of  this script?

If this is to test something, why not just write a unit test?

2019-07-21 17:34 UTC, taegyunkim commented on chipc/generator_tester.py
> +    alu_file = argv[1]
Consider using argparse package.

2019-07-21 17:34 UTC, taegyunkim commented on chipc/sketch_generator.py
> +
Remove unnecessary newline.

2019-07-21 17:34 UTC, taegyunkim commented on chipc/sketch_generator.py
> +
Remove unnecessary newline

2019-07-21 17:34 UTC, taegyunkim commented on chipc/templates/router_data_path_sketch_synthesized_allocation.j2
> +        input_0_{{field_number}} = state_and_packet.pkt_{{field_number}};
Agree with @anirudhSK

2019-07-21 17:34 UTC, taegyunkim commented on example_alus/stateless_alus/stateless_alu.alu
> +// Max value of opcode is 19
Same goes to this file, as @anirudhSK commented.

2019-07-22 23:35 UTC, anirudhSK commented
Currently, the AppVeyor tests seem to be failing because of the SKETCH bug here: https://lists.csail.mit.edu/pipermail/sketchusers/2019-July/000092.html @taegyunkim: is there a way to work around the bug from our side before it's fixed by SKETCH?

2019-07-23 17:33 UTC, anirudhSK approved these changes

2019-07-23 23:21 UTC, taegyunkim approved these changes

2019-07-23 23:25 UTC, merged