Pass constant vector(which store all constants appear in original program) to sketch
chipmunk-project/chipmunk pull request #158
Opened 2019-07-26 02:29 UTC by XiangyuG

2019-07-26 13:30 UTC, taegyunkim requested changes

2019-07-26 13:30 UTC, taegyunkim commented on chipc/direct_solver.py
> +    parser.add_argument(
I don't think this argument is necessary, if you change above constant-set argument to a list of strings. You can take the log of the size. 

Let's avoid the pattern that you add an argument that can be computed from another argument.

2019-07-26 13:30 UTC, taegyunkim commented on chipc/direct_solver.py
> +    parser.add_argument(
Instead of parsing string list, you can try using nargs option and parse multiple arguments separated by whitespace into a list. 

https://github.com/chipmunk-project/chipmunk/blob/a27366c9a6db1e2f59d86d7b30c9a4b9d6a39ea7/chipc/iterative_solver.py#L97
https://docs.python.org/3.5/library/argparse.html#the-add-argument-method

2019-07-26 13:30 UTC, taegyunkim commented on chipc/sketch_generator.py
> +            str(constant_set.count(',')+1) + \
As mentioned in another comment, how about parsing into a list and using len(constant_set) ?

2019-07-26 16:51 UTC, XiangyuG commented on chipc/sketch_generator.py
> +            str(constant_set.count(',')+1) + \
The reason why I use this method is that constant_vector will output the vector with the formula {0,1,2,3}, so I directly pass a string rather than pass a list

2019-07-26 16:51 UTC, XiangyuG commented on chipc/direct_solver.py
> +    parser.add_argument(
Yeah~ I agree. I should delete this argument

2019-07-26 18:27 UTC, XiangyuG commented on chipc/direct_solver.py
> +    parser.add_argument(
I have used another way to force constant_set become a necessary arg. For our case, it looks like pass a string is more suitable due to the output of constant_set binary code

2019-07-26 19:39 UTC, taegyunkim requested changes

2019-07-26 19:39 UTC, taegyunkim commented on chipc/compiler.py
> +                 parallel_sketch, constant_set,
I don't think constant_set_size parameter is necessary. Why not compute it in here?

2019-07-26 19:39 UTC, taegyunkim commented on chipc/iterative_solver.py
> +        help='The content in the constant_set')
It needs more explanation, for example, the format of this argument, because the code to count the length depends on the number of commas in the string.

2019-07-27 01:22 UTC, XiangyuG commented on chipc/iterative_solver.py
> +        help='The content in the constant_set')
Yeah, that is correct. So we should change the help='' to add more explanation?

2019-07-27 01:36 UTC, taegyunkim commented on chipc/iterative_solver.py
> +        help='The content in the constant_set')
Yes, please.

2019-07-27 01:41 UTC, XiangyuG commented on chipc/iterative_solver.py
> +        help='The content in the constant_set')
Sure~

2019-07-27 01:41 UTC, XiangyuG commented on chipc/compiler.py
> +                 parallel_sketch, constant_set,
Yeah! I will remove this unnecessary parameter

2019-07-27 14:11 UTC, taegyunkim reviewed
So overall, this pull request is based on the assumption that we might only need to search for constants that appear in the original program instead of searching for all constants, right?

2019-07-27 14:33 UTC, XiangyuG commented
> So overall, this pull request is based on the assumption that we might only need to search for constants that appear in the original program instead of searching for all constants, right?

Yeah. I mean it will store the constants that appears in original program and search only for those. Compared with searching for all constants such as all integer in 10-bit size, the search space is much smaller.

2019-07-27 14:41 UTC, taegyunkim approved these changes

2019-07-27 15:50 UTC, merged