Add slicing algo
chipmunk-project/chipmunk pull request #201
Opened 2020-01-05 03:23 UTC by XiangyuG

We want to use slicing Algo to speed up synthesis time. 

There are three main parts of slicing, slicing the spec (divide the spec into pieces where each piece is responsible for synthesis one particular packet field or stateful group), slicing the grid size (we try different grid size in parallel because in most cases the slicing problem is simple enough to finish quickly with small grid size) and slicing the input packet field where we create one influence table before synthesis and only feed those packet fields that have influence on our target spec.

2020-01-05 15:35 UTC, taegyunkim reviewed
Do you use separate script or code to make use of these new options?

2020-01-05 15:35 UTC, taegyunkim commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
Why [0][1]?

2020-01-05 20:12 UTC, XiangyuG commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
Because we can get the state_group_info through the function get_state_group_info() in chipc/utils.py.
list(state_group_info.items()) specifies the num of state groups i.e. [('1', OrderedSet(['0'])), ('0', OrderedSet(['0']))]
list(state_group_info.items())[0] randomly picks up one out of all state groups
list(state_group_info.items())[0][1] specifies the members in that group
len(list(state_group_info.items())[0][1]) specifies the size of each state-group

2020-01-05 21:58 UTC, taegyunkim commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
OK, but why use 1 for the index?

2020-01-06 02:18 UTC, anirudhSK requested changes

2020-01-06 02:18 UTC, anirudhSK commented on chipc/compiler.py
> +                 input_packet=[]):
We should call this input_packet_fields instead of input_packet. We should also call pkt_fields_to_check and state_groups_to_check output_packet_fields and output_state_groups.

2020-01-06 02:18 UTC, anirudhSK commented on chipc/templates/router_data_path_sketch.j2
> +        // loop.index starts from 1 that's why we need to -1
What changed in this commit that is causing us to use loop.index here instead of field_number?

2020-01-06 02:18 UTC, anirudhSK commented on chipc/iterative_solver.py
> +    if pkt_fields_to_check is None and state_group_to_check is None:
Lines 78 to 114 have the bulk of the new code. Can we add some comments describing what those lines are trying to accomplish?

2020-01-06 02:27 UTC, taegyunkim commented on chipc/iterative_solver.py
> +        help='Show the actual packet fields used as the input of spec.')
Could you elaborate on what this means?

2020-01-06 04:44 UTC, XiangyuG commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
Because [1] specifies the number of members in each group. For example 
list(state_group_info.items()) = [('1', OrderedSet(['0'])), ('0', OrderedSet(['0']))]
list(state_group_info.items())[0] =  ('1', OrderedSet(['0']))
list(state_group_info.items())[0][1] = OrderedSet(['0'])
len(list(state_group_info.items())[0][1]) = 1

2020-01-06 04:48 UTC, XiangyuG commented on chipc/templates/router_data_path_sketch.j2
> +        // loop.index starts from 1 that's why we need to -1
This is a really good point where I modified this after running some experiment. Basically, the explanation can be this. 
Suppose we have 1 phvs per stage to receive pkt_1 as input 
we should set **input_0_0 = state_and_packet.pkt_1** 
But the previous case when we use field_number will be 
**input_0_1 = state_and_packet.pkt_1** which will cause a syntax error because there should not be input_0_1 when there is only 1 phv container per stage

2020-01-06 04:50 UTC, XiangyuG commented on chipc/iterative_solver.py
> +        help='Show the actual packet fields used as the input of spec.')
This is a really good point!! I should elaborate on this part.
Basically, it means for one specific slicing (for example pkt_0), we only need to choose those packet fields which will influence the final output of pkt_0 to feed into the phv containers in stage_0.

2020-01-06 05:02 UTC, XiangyuG commented on chipc/compiler.py
> +                 input_packet=[]):
Done!!

2020-01-06 05:36 UTC, XiangyuG commented on chipc/iterative_solver.py
> +    if pkt_fields_to_check is None and state_group_to_check is None:
Done!

2020-01-06 16:46 UTC, taegyunkim commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
ok, why not 0?

2020-01-06 19:32 UTC, taegyunkim requested changes

2020-01-06 19:32 UTC, taegyunkim commented on chipc/iterative_solver.py
> +        '--input-packet',
At least the name of this argument or the description needs to be updated. 

This is intended to tell the user/program that the fields or numbers specified here influence the packet fields/states that we want to check correctness for.  For example, in blue_decrease.sk, packet field pkt_1 depends on pkt_0. That's why the test case specifies --input-packet=0. 

    def test_blue_decrease_1_1_sub_cex_mode_pkt0(self):
        self.assertEqual(
            0,
            iterative_solver.main([
                'iterative_solver',
                path.join(SPEC_DIR, 'blue_decrease.sk'),
                path.join(STATEFUL_ALU_DIR, 'sub.alu'),
                path.join(STATELESS_ALU_DIR, 'stateless_alu.alu'),
                '1', '1', '0,1,2,3', '10',
                '--pkt-fields=0',
                '--input-packet', '0']),
        )

2020-01-06 19:32 UTC, taegyunkim commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
len(state_group_info.values()[0])

Probably better to make a comment regarding the types of 
state_group_info: this is an OrderedDict()
state_group_info.values(): iterable of OrderedSet()

2020-01-06 19:32 UTC, taegyunkim commented on chipc/templates/router_data_path_sketch.j2
> +        // loop.index starts from 1 that's why we need to -1
You probably get away from this by using enumerate(input_packet_fields) for Python code but jinja2 doesn't support that. 

```
for i, field_number in enumerate(input_packet_fields):
   ...
```

2020-01-06 21:13 UTC, XiangyuG commented on chipc/iterative_solver.py
> +    group_size = len(list(state_group_info.items())[0][1])
Done!

2020-01-06 21:21 UTC, XiangyuG commented on chipc/iterative_solver.py
> +        '--input-packet',
Done!

2020-01-06 22:14 UTC, taegyunkim approved these changes

2020-01-06 23:08 UTC, anirudhSK approved these changes

2020-01-06 23:09 UTC, merged