Handle multiple states in alu
chipmunk-project/chipmunk pull request #35
Opened 2019-03-08 14:35 UTC by anirudhSK

2019-03-08 14:47 UTC, taegyunkim requested changes

2019-03-08 14:47 UTC, taegyunkim commented on example_alus/pair.stateful_alu
> +  state_1 = Opt(state_1) + arith_op(Mux3(pkt_1, pkt_2, C()),  Mux3(pkt_1, pkt_2, C()))
Antlr is complaining when I use this alu. 

line 7:2 mismatched input 'state_1' expecting '}'                                                                                                                                                                                                                                                                              
line 10:2 mismatched input 'state_1' expecting '}'                                                                                                                                                                                                                                                                             
line 7:2 mismatched input 'state_1' expecting '}'                                                                                                                                                                                                                                                                              
line 10:2 mismatched input 'state_1' expecting '}'

I'm trying to understand why this is happening.

2019-03-08 14:56 UTC, anirudhSK commented on example_alus/pair.stateful_alu
> +  state_1 = Opt(state_1) + arith_op(Mux3(pkt_1, pkt_2, C()),  Mux3(pkt_1, pkt_2, C()))
The grammar has changed. Can you run:
1. git clean -xfd (note that this removes all untracked files)
2. antlr4 -Dlanguage=Python3 -visitor stateful_alu.g4

This will regenerate the grammar. After regenerating the grammar, can you see if your error persists?

2019-03-08 15:04 UTC, taegyunkim requested changes
```C
|StateGroup| pair_2_2_stateful_alu_0_0(ref |StateGroup| state_group, int pkt_1,int pkt_2,int pkt_3,int pkt_4,int pkt_5, int Mux3_0,int Mux3_1,int Mux3_2,int Mux3_3,int Mux3_4,int Mux3_5,int Mux3_6,int Mux3_7,int Mux3_8,int Mux3_9,int Opt_0,int Opt_1,int arith_op_0,int arith_op_1,int const_0,int const_1,int const_2,   int const_3,int const_4,int const_5,int rel_op_0,int rel_op_1)  {
  |StateGroup| old_state_group = state_group;                                        
  int state_0 = state_group.state_0;                                              
  int state_1 = state_group.state_1;
  if (pair_2_2_stateful_alu_0_0_rel_op_0(pair_2_2_stateful_alu_0_0_Mux3_0(state_0,state_1,Mux3_0)+pair_2_2_stateful_alu_0_0_Mux3_1(pkt_1,pkt_2,Mux3_1)-pair_2_2_stateful_alu_0_0_Mux3_2(pkt_1,pkt_2,Mux3_2),pair_2_2_stateful_alu_0_0_C_0(const_0),rel_op_0)) {
    if (pair_2_2_stateful_alu_0_0_rel_op_1(pair_2_2_stateful_alu_0_0_Mux3_3(state_0,state_1,Mux3_3)+pair_2_2_stateful_alu_0_0_Mux3_4(pkt_1,pkt_2,Mux3_4)-pair_2_2_stateful_alu_0_0_Mux3_5(pkt_1,pkt_2,Mux3_5),pair_2_2_stateful_alu_0_0_C_1(const_1),rel_op_1)) {
state_0 = pair_2_2_stateful_alu_0_0_Opt_0(state_0,Opt_0)+            pair_2_2_stateful_alu_0_0_arith_op_0(pair_2_2_stateful_alu_0_0_Mux3_6(pkt_1,pkt_2,pair_2_2_stateful_alu_0_0_C_2(const_2),Mux3_6),pair_2_2_stateful_alu_0_0_Mux3_7(pkt_1,pkt_2,pair_2_2_stateful_alu_0_0_C_3(const_3),Mux3_7),arith_op_0);
    } 
  }  else { state_0 = pair_2_2_stateful_alu_0_0_Opt_1(state_0,Opt_1)+                     pair_2_2_stateful_alu_0_0_arith_op_1(pair_2_2_stateful_alu_0_0_Mux3_8(pkt_1,pkt_2,pair_2_2_stateful_alu_0_0_C_4(const_4),Mux3_8),pair_2_2_stateful_alu_0_0_Mux3_9(pkt_1,pkt_2,pair_2_2_stateful_alu_0_0_C_5(const_5),Mux3_9),arith_op_1);}
state_group.state_0 = state_0;                                                      
state_group.state_1 = state_1;                                                      
; return old_state_group;                                                           
}                      
```

This is generated in this branch with 
`python3 chipmunk.py example_specs/simple.sk example_alus/pair.stateful_alu 2 2 codegen pair_2_2 serial`

And it doesn't output update for state_1 as in [pair.stateful_alu#7](https://github.com/taegyunkim/chipmunk/blob/multiple_states_in_alu/example_alus/pair.stateful_alu#L7)

Is this expected?

2019-03-08 15:05 UTC, taegyunkim commented on example_alus/pair.stateful_alu
> +  state_1 = Opt(state_1) + arith_op(Mux3(pkt_1, pkt_2, C()),  Mux3(pkt_1, pkt_2, C()))
Oh, I always forget that.

2019-03-08 15:07 UTC, taegyunkim approved these changes

2019-03-08 15:07 UTC, taegyunkim commented
My second comment was also coming from the fact that I didn't update grammar.

2019-03-08 15:12 UTC, merged

2019-03-10 21:26 UTC, taegyunkim commented on compiler.py
> +            loader=FileSystemLoader('./templates'), undefined=StrictUndefined, trim_blocks = True, lstrip_blocks = True)
Are these options safe to apply to other Environments? in repeated_solver.py and optverify.py?

2019-03-10 21:33 UTC, anirudhSK commented on compiler.py
> +            loader=FileSystemLoader('./templates'), undefined=StrictUndefined, trim_blocks = True, lstrip_blocks = True)
Yes.