Fix bug in iterative solver.
chipmunk-project/chipmunk pull request #84
Opened 2019-04-15 17:33 UTC by anirudhSK

2019-04-15 17:51 UTC, taegyunkim requested changes

2019-04-15 17:51 UTC, taegyunkim commented on chipc/iterative_solver.py
> +    state_group_info = get_info_of_state_groups(Path(args.program_file).read_text())
Instead of reading the program file text twice here and inline 106, store it in a variable and use it in 106 and here.

2019-04-15 17:51 UTC, taegyunkim commented on chipc/utils.py
> +def get_info_of_state_groups(program):
Could you add tests in tests/test_utils.py?

2019-04-15 17:51 UTC, taegyunkim commented on chipc/utils.py
> +    state_group_info = findall(r'state_and_packet.state_group_(\d+)_state_(\d+)',program)
If you look at the function below, it also counts the number of state_groups, why not change below function to only calculate num_pkt_fields and change its name to get_num_pkt_fields?

2019-04-15 18:05 UTC, anirudhSK commented
1. There is a bug here: https://github.com/chipmunk-project/chipmunk/blob/b524be72e69214410bef57617751fe8d61e33cbb/chipc/iterative_solver.py#L51 because group_0 is hardcoded.

2. We should ensure all state groups are filled up by creating dummy state variables if required. For instance, if we have 3 state variables and a max. group size of 2, we need to create 3 real variables:
state_group_0_state_0
state_group_0_state_1
state_group_1_state_0

AND one dummy variable:

state_group_1_state_1

This should be done in the grouper binary.

2019-04-15 18:39 UTC, XiangyuG commented on chipc/utils.py
> +    state_group_info = findall(r'state_and_packet.state_group_(\d+)_state_(\d+)',program)
They are two different things so we have to do separately

2019-04-18 12:29 UTC, taegyunkim commented
Is this ready for review? I still see my comments unresolved.

2019-04-18 12:53 UTC, XiangyuG commented
> Is this ready for review? I still see my comments unresolved.

>Let me add one more test before your review.

2019-04-18 14:17 UTC, XiangyuG commented on chipc/utils.py
> +def get_info_of_state_groups(program):
I add the test for get_info_of_state_groups function which has passed the test. But I am still a little bit confused about this part """with self.assertRaises(AssertionError):
            get_info_of_state_groups("state_and_packet.state_group_1_state_0")"""
So can you help me look at it or we can talk when you come to CDS.

2019-04-18 14:40 UTC, taegyunkim approved these changes

2019-04-18 17:27 UTC, merged