Store generated file each iteration
chipmunk-project/chipmunk pull request #95
Opened 2019-04-23 15:19 UTC by XiangyuG

Store every sketch running file's result
Pass iteration # into the parameter
Generate all files from each iteration

2019-04-23 15:28 UTC, taegyunkim requested changes

2019-04-23 15:28 UTC, taegyunkim commented on tests/test_chipmunk.py
> +            self.assertEqual(compiler.serial_codegen(0)[0], 0,
Instead of setting 0 for num_of_iteration in every function here, why not set a default value in function definition?

2019-04-23 15:28 UTC, taegyunkim commented on chipc/compiler.py
> +    def serial_codegen(self, num_of_iteration, additional_constraints=[],
num_of_iteration doesn't make sense for a single invocation. 
Also, this is from the count variable from iterative solver, right? How about iter_cnt with default value None.

2019-04-23 15:28 UTC, taegyunkim commented on chipc/compiler.py
> +                  "_output.txt", 'w') as outputfile:
output_file

2019-04-23 15:29 UTC, XiangyuG commented on tests/test_chipmunk.py
> +            self.assertEqual(compiler.serial_codegen(0)[0], 0,
So you mean add one default parameter in the function definition and use it later?

2019-04-23 15:29 UTC, taegyunkim commented
https://ci.appveyor.com/project/anirudhSK/chipmunk-hhg5f/builds/24045099

Appveyor failed. Please fix.

2019-04-23 15:32 UTC, taegyunkim commented on tests/test_chipmunk.py
> +            self.assertEqual(compiler.serial_codegen(0)[0], 0,
Yeah, see my comment in chipc/compiler.py.

2019-04-23 15:34 UTC, XiangyuG commented on chipc/compiler.py
> +    def serial_codegen(self, num_of_iteration, additional_constraints=[],
I totally agree with your idea.
BTW, what you mean by iter_cnt with default value None?

2019-04-23 15:35 UTC, XiangyuG commented on chipc/compiler.py
> +                  "_output.txt", 'w') as outputfile:
Yeah. Just for clarification, as for this issue, I need to change the file in my machine and git commit git push it to our repo?

2019-04-23 15:35 UTC, taegyunkim commented on chipc/compiler.py
> +    def serial_codegen(self, num_of_iteration, additional_constraints=[],
1. change the num_of_iteration to iter_cnt
2. Set the default value None

Then you might have to change how you use num_of_iteration below. 

```Python
def serial_codegen(self, iter_cnt=None, additional_constraints=[]. 
```

2019-04-23 15:37 UTC, taegyunkim commented on chipc/compiler.py
> +                  "_output.txt", 'w') as outputfile:
Just simply modify the file in your local machine and commit.

2019-04-23 15:40 UTC, taegyunkim commented on chipc/compiler.py
> +                  "_output.txt", 'w') as outputfile:
And push

2019-04-24 00:48 UTC, taegyunkim commented
Still the appveyor script is failing. If you carefully look at the console output, a test fails. Pleas take a look.

2019-04-24 01:05 UTC, taegyunkim commented
If you do
$> git clean -xfd
$> pip install -e .
$> python tests/test_chipmunk.py TestDirectSolver.test_simple_raw_succeeds_with_two_two_grid

this test will fail
The reason this passes when you do $> nosetests or $> python -m unittest is that
one of the other test cases actually generates the file it uses,
However since you have changed the name of file that is being generated within this pull request
you have to update the name of file it uses within the test to pass

2019-04-24 01:56 UTC, taegyunkim requested changes

2019-04-24 01:56 UTC, taegyunkim commented on chipc/compiler.py
>              "--beopt:writeSMT " + self.sketch_name + ".smt2 " +
Can you also update this line and line 228? We would get different smt2 file for different sketch files.

2019-04-24 02:00 UTC, XiangyuG commented on chipc/compiler.py
>              "--beopt:writeSMT " + self.sketch_name + ".smt2 " +
So what you mean by updating this line?

2019-04-24 02:03 UTC, taegyunkim requested changes

2019-04-24 02:03 UTC, taegyunkim commented on chipc/compiler.py
>              "--beopt:writeSMT " + self.sketch_name + ".smt2 " +
--beopt:writeSMT takes a filename to write smt2 file to. Then in line 228, we open that file and parse it. #91 pull request has changed the way we run sol_verify. We no longer use sketch to verify the solution, and we use z3 instead. The interesting file/bit in this process is the smt2 file instead of sketch file.

2019-04-24 02:06 UTC, XiangyuG commented on chipc/compiler.py
>              "--beopt:writeSMT " + self.sketch_name + ".smt2 " +
Yeah, I understand your point. But I am confused which change I should make? Do you mean store the smt2 file?

2019-04-24 02:12 UTC, taegyunkim commented on chipc/compiler.py
>              "--beopt:writeSMT " + self.sketch_name + ".smt2 " +
What I want you to do is update the Python code to also output iter_cnt in the filename for .smt2 file.

2019-04-24 02:21 UTC, XiangyuG commented on chipc/compiler.py
>              "--beopt:writeSMT " + self.sketch_name + ".smt2 " +
I see. I think I have finished this step.

2019-04-24 03:26 UTC, taegyunkim requested changes

2019-04-24 03:26 UTC, taegyunkim commented on chipc/compiler.py
> +        with open(self.sketch_name + "_sol_verify_iteration_" +
I don't think this is necessary as the sketch verification is now run with --slv-timeout=0.001, which basically turns it off for most of the cases. It doesn't make sense to output this file. 

Delete lines 234, 235, 236.

2019-04-24 03:28 UTC, taegyunkim requested changes

2019-04-24 03:28 UTC, taegyunkim commented on chipc/compiler.py
> +            str(iter_cnt) + ".smt2 " +
You also need to change the line where we parse smt2 file back.

2019-04-24 03:28 UTC, XiangyuG commented on chipc/compiler.py
> +        with open(self.sketch_name + "_sol_verify_iteration_" +
Yeah, we do not use this file. But what I am concern is that do we still need to store this file because .smt2 file is generated from sketch file?

2019-04-24 03:31 UTC, taegyunkim requested changes

2019-04-24 03:31 UTC, taegyunkim commented on chipc/compiler.py
> +        with open(self.sketch_name + "_sol_verify_iteration_" +
Note that you're saving the output returned from sketch call in line 227. As far as I know, the output is not used to generate smt2 file, the input sk file to the sketch call is used to generate it.

2019-04-24 03:32 UTC, XiangyuG commented on chipc/compiler.py
> +        with open(self.sketch_name + "_sol_verify_iteration_" +
I see. I will delete these three lines.

2019-04-24 03:32 UTC, taegyunkim commented on chipc/compiler.py
> +            str(iter_cnt) + ".smt2 " +
https://ci.appveyor.com/project/anirudhSK/chipmunk-hhg5f/builds/24059434 
The appveyor failure is coming from not updating that part.

2019-04-24 03:32 UTC, XiangyuG commented on chipc/compiler.py
> +            str(iter_cnt) + ".smt2 " +
Where do we parse smt2 file back?

2019-04-24 03:34 UTC, taegyunkim commented on chipc/compiler.py
> +            str(iter_cnt) + ".smt2 " +
Just scroll down. 
`        formula = z3.parse_smt2_file(self.sketch_name + ".smt2")[0]`

2019-04-24 03:48 UTC, XiangyuG commented on chipc/compiler.py
> +            str(iter_cnt) + ".smt2 " +
Thanks. Done

2019-04-24 04:24 UTC, taegyunkim approved these changes
Thanks, Xiangyu, hope all these review comments were not too much for you.

2019-04-24 04:30 UTC, merged